-- Fix search_path for area_to_role function
CREATE OR REPLACE FUNCTION public.area_to_role(area TEXT)
RETURNS app_role
LANGUAGE plpgsql
STABLE
SECURITY INVOKER
SET search_path = public
AS $$
BEGIN
  RETURN CASE 
    WHEN area ILIKE '%CENTRO CIVICO%ENGENHARIA%' THEN 'CENTRO_CIVICO_ENGENHARIA'::app_role
    WHEN area ILIKE '%CENTRO CIVICO%GPOG%' THEN 'CENTRO_CIVICO_GPOG'::app_role
    WHEN area ILIKE '%CENTRO DE EVENTOS%' THEN 'GERENCIA_CENTRO_EVENTOS'::app_role
    WHEN area ILIKE '%COMPRAS%LOGISTICA%' THEN 'GERENCIA_COMPRAS_LOGISTICA'::app_role
    WHEN area ILIKE '%CONTABILIDADE%' THEN 'GERENCIA_CONTABILIDADE_PATRIMONIO_FINANCEIRO'::app_role
    WHEN area ILIKE '%FACILITIES%' THEN 'GERENCIA_FACILITIES'::app_role
    WHEN area ILIKE '%PERFORMANCE%CANAIS%' THEN 'GERENCIA_PERFORMANCE_CANAIS_VENDAS'::app_role
    WHEN area ILIKE '%PLANEJAMENTO%ORCAMENTO%' THEN 'GERENCIA_PLANEJAMENTO_ORCAMENTO'::app_role
    WHEN area ILIKE '%PROJETOS%PROCESSOS%' OR area ILIKE '%MELHORIA CONTINUA%' THEN 'GERENCIA_PROJETOS_PROCESSOS_MELHORIA'::app_role
    WHEN area ILIKE '%RECURSOS HUMANOS%' THEN 'GERENCIA_RECURSOS_HUMANOS'::app_role
    WHEN area ILIKE '%IEL%' THEN 'GERENCIA_RELACIONAMENTO_IEL'::app_role
    WHEN area ILIKE '%RISCOS%COMPLIANCE%' THEN 'GERENCIA_RISCOS_COMPLIANCE'::app_role
    WHEN area ILIKE '%TECNOLOGIA%INFORMACAO%' THEN 'GERENCIA_TECNOLOGIA_INFORMACAO'::app_role
    ELSE NULL
  END;
END;
$$;

-- Fix search_path for update_updated_at function
CREATE OR REPLACE FUNCTION public.update_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public
AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;